// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qjzoefbunmhpafcqbbtl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFqem9lZmJ1bm1ocGFmY3FiYnRsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY1MDg5OTAsImV4cCI6MjA3MjA4NDk5MH0.ewM1knYlreKtdW6QpBjAU8BdyP7ssMYLFyEzuKImbvk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});